### ISSUE TITLE
Test?

### ISSUE THREAD

**Issue by zvezdochiot** [richgel999/fpng#1]
:question: Maybe add `CImg` (https://github.com/dtschump/CImg) and `libiio` (https://github.com/mnhrdt/iio) in test?

**Comment by richgel999** [comment]
libiio looks interesting - I'll check it out.

**Comment by zvezdochiot** [comment]
Hi @richgel999 .

`libiio` is used in many articles and papers in ![IPOL](https://www.ipol.im/static/IPOL-header-logo.png) [IPOL Journal](http://www.ipol.im/).

See also https://github.com/IPOL-Fork
