### ISSUE TITLE
Cannot load my png-file...

### ISSUE THREAD

**Issue by inversepixel** [richgel999/fpng#11]
Hello!

I'm trying to add FPNG to our image error metric called FLIP (https://github.com/NVlabs/flip/) because we need faster PNG loading.
Unfortunately, I cannot load the first image I tried with:
![reference](https://user-images.githubusercontent.com/26431839/148960998-83014569-0d28-49ba-91f2-9edba02e825c.png)

The code exits on line 3033 in fpng.cpp:
`if ((idat_ofs) || (!found_fdec_chunk))`
`        return FPNG_DECODE_NOT_FPNG;`

The cause is that `found_fdec_chunk==false`.
Any ideas on what can be wrong? The image can be loaded by `stbi_image.h` and PhotoShop.

Thanks in advance!
/Tomas

**Comment by richgel999** [comment]
OK - I'll check it out.

**Comment by richgel999** [comment]
Strange - just tested your image under Windows using clang. Worked OK. I've attached the FPNG compressed .PNG file, along with the command line output. There's a known problem on Apple M1, possibly an endian issue, that's on my TODO list to fix. Which platform/compiler are you testing it on? Could you please attach the FPNG generated PNG? Thanks!

![fpng](https://user-images.githubusercontent.com/6934809/149021089-71456416-719a-4655-bf4a-8b1f92589983.png)

![image](https://user-images.githubusercontent.com/6934809/149021017-37094c11-4931-4d0c-8add-333512cc303e.png)

**Comment by richgel999** [comment]
[pngcheck](http://www.libpng.org/pub/png/apps/pngcheck.html) output on the generated PNG file (attached to my prior reply):

![image](https://user-images.githubusercontent.com/6934809/149021497-b841b704-c078-4cec-a5d3-e8e3c9e7d332.png)

Could you try the pngcheck tool on the written png? Also, if you run the fpng_test tool on your PNG, it'll compress using FPNG and write a file named "fpng.png". Does the fpng_test tool work properly on your test app? Appreciate any more info you can provide.

**Comment by richgel999** [comment]
OK - I reread your report. So you're aware, fpng's decompressor is not a general purpose PNG reader (yet). It can *only* read PNG's generated using fpng. fpng is a fast encoder with an associated decoder. If it returns FPNG_DECODE_NOT_FPNG, that means the PNG wasn't generated using fpng, and you should fall back to a general purpose PNG decoder. (I thought your report was saying that a PNG file *written* by FPNG wasn't able to be loaded.) Sorry for any confusion.

If you need a fast PNG loader, I highly recommend Wuffs:
https://github.com/google/wuffs/tree/main/release/c

**Comment by inversepixel** [comment]
Oh, that was not immediately clear to me. I read " fpng is a very fast C++ .PNG image reader/writer for 24/32bpp images." and then assumed that I could read any png. Thanks a lot for the clarification.
I'll try Wuffs.
