### ISSUE TITLE
QOI has a more comprehensive test suite

### ISSUE THREAD

**Issue by nigeltao** [richgel999/fpng#13]
fpng's top-level README.md says "_the_ [emphasis added] 184 QOI test images (note 182 of the qoi test images don't have alpha channels, so this is almost entirely a 24bpp test)".

QOI updated its test suite a month ago (https://github.com/phoboslab/qoi/issues/69). The new suite contains 2848 images.

**Comment by richgel999** [comment]
We now have two PNG writers and one JPEG XL writer that are faster and compress better than QOI (especially with 32bpp).  For fast PNG reading, we have Wuffs, which is 2-2.5x faster than other readers. So I'm not too concerned about comparisons to QOI now. I'll update the main page soon.

![image](https://user-images.githubusercontent.com/6934809/149885306-483add37-f8d3-464e-9ec3-02957dbf18da.png)

From:
https://twitter.com/jonsneyers/status/1483000547934449668
