### ISSUE TITLE
Not an Issue - Just Need Help

### ISSUE THREAD

**Issue by zayne-anthony** [richgel999/fpng#17]
Hey! So I am I'm new to all of this in terms of C. I am just a web dev and trying to figure out how to maybe compress PNG images to be usable (Size of File for Speed) on web. Was looking at this and QOI. But this one looks a lot more promising due to it being compatible  with PNG decoders already. Anyway, I am doing the Testing section and trying to convert my PNG to FPNG but I am just getting a bigger file of my original PNG or the same size.

Am I do doing it right?
```
// CMD Line in ./fpng_main/bin

./fpng.exe -s test.png
```

Is there something else I need to be doing? Sorry again, I am a complete newbie to this type of stuff lol

**Comment by hallonterror** [comment]
The goal of this project is not too make the files smaller on disk, but to provide fast encoding and decoding. 

The file may typically be larger than that from a standard png encoder.

**Comment by zayne-anthony** [comment]
> The goal of this project is not too make the files smaller on disk, but to provide fast encoding and decoding.
> 
> The file may typically be larger than that from a standard png encoder.

Oh okay, may be a stupid question but in term would this be faster than a normal png, lets say on a site? Since its decoding it faster?

**Comment by hallonterror** [comment]
In principle yes, but for best performance the browser should use an optimized decoder. 

If I understood correctly the goal here was to prove that png can be encoded and decoded at similar speeds as qoi. For that to be true however both the encoder and decoder should be used. In general decoding is however the more cumbersome part of the png format processing. 

I’ve been looking into alternatives for a while. My needs are quite special though. A promising format in general might be jpeg xl. It features lossless compression with fast and progressive decoding. Check it out. Support for this format is likely within a year or so I would expect. Maybe also webp if your main concern is fast decoding and want something with decent support already.
