### ISSUE TITLE
Security contact point?

### ISSUE THREAD

**Issue by NBickford-NV** [richgel999/fpng#21]
Hi Rich! Thanks for developing fpng.

Is there a recommended contact point (for instance, an email address or a secure bug tracker) to responsibly disclose potential security vulnerabilities to the fpng project?

If it's not too much trouble, it could be nice to have a `SECURITY.md` file to answer questions like this in the future; [GitHub can display these](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) in the Security tab.

Thanks!

--Neil

**Comment by richgel999** [comment]
Yes richgel99 at protonmail.com. I'll add a SECURITY.md file.

**Comment by NBickford-NV** [comment]
Thank you Rich! Please feel free to close this issue.

**Comment by NBickford-NV** [comment]
Hi Rich! I sent an email to the security address in June from nbickford@nvidia.com, but did not receive a response. I'll try re-sending it from an @gmail.com address; could you check that @nvidia.com addresses aren't blocked for you? Thanks!

**Comment by richgel999** [comment]
Hi - Yes I'm here. My best email for stuff like this is rich@binomial.info. I get swamped on the above address.
Regards,
-Rich
