### ISSUE TITLE
Can fpng be header only

### ISSUE THREAD

**Issue by ArashPartow** [richgel999/fpng#3]
Being header only will make it much easier to integrate into projects.

**Comment by richgel999** [comment]
Yes, that would be trivial to do. I'm going to do that tonight. Thanks for the suggestion.

**Comment by richgel999** [comment]
How about this: 

#include "fpng.cpp", then #include "fpng.h" in *one* place. 
Then #include "fpng.h" everywhere else?

This is easier than a single source file header, because you don't need to hunt down which implementation #define to use.

**Comment by ArashPartow** [comment]
Sounds reasonable.  :+1:
