### ISSUE TITLE
Possible (likely innocuous) typo in chunk name parsing

### ISSUE THREAD

**Issue by Benjins** [richgel999/fpng#5]
I was looking over the source code, and I noticed this oddity in the code for detecting chunk type

https://github.com/richgel999/fpng/blob/b964f657bd3ace341df47fab3c249a24c6eac995/src/fpng.cpp#L2520-L2526

```
for (uint32_t i = 0; i < 4; i++)
{
	const uint8_t c = pChunk->m_type[0];
```

It appears that it's checking for non-alphabetical characters in the chunk type string, but it's only repeatedly checking that that's true for the first character in the type. I suspect `m_type[0]` was meant to be `m_type[i]`

I don't believe that this would cause problems, since the other checks should still reject any not-recognized chunk types

**Comment by richgel999** [comment]
Whoops - that's a typo! Thanks I'll fix it now.

**Comment by richgel999** [comment]
Fixed. Thanks a bunch for the report!
