### ISSUE TITLE
Request a valid version number tag / release.

### ISSUE THREAD

**Issue by waruqi** [richgel999/fpng#6]
fpng is great, I am adding it to Xmake's package management repository, it requires a valid version number to do the version of the package, and then download the specified tar.gz through the version number. like this, v1.0, v1.0.1, ...

see https://github.com/xmake-io/xmake-repo/pull/812

Although even if there is no version number, I can also implement it through git commit + fake version, but this is not recommended.

I hope that fpng can have a good version tag list, thank you very much.

**Comment by richgel999** [comment]
Thanks - sure I can add a version. What would work best for you? I can add it to the source for sure.

**Comment by waruqi** [comment]
> Thanks - sure I can add a version. What would work best for you? I can add it to the source for sure.

need only one git tag with version number

**Comment by richgel999** [comment]
Got it! I'll update these tags as I improve it. Thanks!
https://github.com/richgel999/fpng/releases/tag/v1.0.0

**Comment by richgel999** [comment]
Latest tag:
https://github.com/richgel999/fpng/releases/tag/v1.0.1

**Comment by waruqi** [comment]
Thanks, I have updated to v1.0.1 https://github.com/xmake-io/xmake-repo/pull/815

**Comment by zvezdochiot** [comment]
Hi all.

Why is the "v" character used in tags? This breaks the digital order of the versions.

**Comment by richgel999** [comment]
Fixed:
https://github.com/richgel999/fpng/releases/tag/1.0.4
