### ISSUE TITLE
Compilation fails on Apple M1

### ISSUE THREAD

**Issue by rossant** [richgel999/fpng#8]
I don't manage to compile fpng on my Apple MacBook Pro M1 (ARM). I get the following compilation error:

```
fpng.cpp:304:22: error: invalid output constraint '+b' in asm
                __asm__("cpuid;" : "+b"(ebx), "+a"(eax), "+c"(ecx), "=d"(edx));
 ``` 

System: 

```
$ uname -a
Darwin macbookpro 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
```

```
/Library/Developer/CommandLineTools/usr/bin/c++ --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Any help appreciated! Thanks.

**Comment by richgel999** [comment]
Thanks - I have an M1 here but I didn't get a chance to compile it there yet. I'll fix this issue sometime today.

I see the issue - this code needs to be put into a #ifndef FPNG_NO_SSE block:

#ifndef _MSC_VER
	static void do_cpuid(uint32_t eax, uint32_t ecx, uint32_t* regs)
	{
		uint32_t ebx = 0, edx = 0;

#if defined(__PIC__) && defined(__i386__)
		__asm__("movl %%ebx, %%edi;"
			"cpuid;"
			"xchgl %%ebx, %%edi;"
			: "=D"(ebx), "+a"(eax), "+c"(ecx), "=d"(edx));
#else
		__asm__("cpuid;" : "+b"(ebx), "+a"(eax), "+c"(ecx), "=d"(edx));
#endif

		regs[0] = eax; regs[1] = ebx; regs[2] = ecx; regs[3] = edx;
	}
#endif

**Comment by rossant** [comment]
Thanks! Your patch does fix the compiler error.

However, my test code doesn't appear to work correctly. I generate a mock image and encode it into a png with both `fpng_encode_image_to_memory()` and `fpng_encode_image_to_file()`. On M1, the former fails while the latter works. On Linux, both work. With `fpng_encode_image_to_memory()`, the output buffer seems to be full of zeros. Am I doing something wrong or might there be an issue with M1?

**Comment by richgel999** [comment]
I've checked in the cpuid fix. 

It's almost certainly a silly bug. I haven't had a chance to test the code on non-x86/x64 machines yet. The code in theory should work (it supports both little/big endian, and non-aligned reads/writes), but I need to test it. I have an M1 sitting next to me, so I'll fix it.

**Comment by sethrj** [comment]
The latest master builds for me on Apple M1 with Monterey and XCode 13.2.

**Comment by richgel999** [comment]
Does it work? I've not had a chance to try it on my M1 yet. Thanks!

**Comment by Sakari369** [comment]
Thanks for writing this, just tested on M1 with Monterey and clang 13.1.6, at least encoding to file works just fine :)
Would be interesting to see benchmark results vs x86 SSE and scalar M1. Maybe I will test that later on my Intel mac also.

**Comment by richgel999** [comment]
Ok thanks for the info! I'm closing this for now.
